id: I9EBEFDD6
source: https://sakyaresearch.org
source_file: null
initial_creation_type: input
imported: '2022-06-18T19:16:28.957362'
last_modified: '2022-06-18T19:16:28.957375'
parser: null
source_metadata:
  title: Maṇḍalavidhi of Akṣobhyavarja Guhyasamāja by Tsong kha pa (1357–1419) (dGa
    ldan block print), colophon excerpt
  author: tsong kha pa blo bzang grags pa/
  description: 'Digital version 1.0 {Wylie}; WYLIE COPY of master xml (completed:
    2022-06-02); revised, thematic TEI markup'
  file_info:
  - 'Language: Wylie'
  - 'Coverage: Excerpt/Colophon'
  - 'Accessible: publicly'
  responibilities:
  - Digital edition:Sakya Research Centre (src)
  - Text input:Mathias Fermer (mf)
  - Editorial process:David Jackson (dj)
  - TEI Encoding:Sakya Research Centre
  - TEI Markup:Mathias Fermer (mf)
  - Revisions/Corrections:Mathias Fermer (mf)
  text_witnesses: https://sakyaresearch.org/sources/1391
  bases:
    8e60:
      title: Maṇḍalavidhi of Akṣobhyavarja Guhyasamāja by Tsong kha pa (1357–1419)
        (dGa ldan block print), colophon excerpt
      order: 1
      base_file: 8e60.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
